# Generated by Django 4.1.1 on 2022-10-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
